import React, { useState } from 'react';
import { useApp } from '../context/AppContext';
import { 
  FileSpreadsheet, 
  FileText, 
  Download, 
  TrendingUp, 
  TrendingDown, 
  DollarSign, 
  Boxes, 
  AlertTriangle, 
  CheckCircle2, 
  Calendar,
  Layers,
  ArrowUpRight,
  ArrowDownRight,
  Printer
} from 'lucide-react';
import { 
  downloadExcelTemplate, 
  exportInventoryToExcel, 
  exportInventoryToPdf, 
  exportSalesToExcel, 
  exportSalesToPdf, 
  exportExpensesToExcel, 
  exportExpensesToPdf 
} from '../utils/excelPdfUtils';
import { formatCurrency } from '../utils/currencyUtils';
import jsPDF from 'jspdf';
import autoTable from 'jspdf-autotable';

export const ReportsCenter: React.FC = () => {
  const { items, sales, expenses, settings, currentUser } = useApp();

  // Metrics Calculations
  const totalCostValuation = items.reduce((acc, i) => acc + (i.stock * i.costPrice), 0);
  const totalRetailValuation = items.reduce((acc, i) => acc + (i.stock * i.sellingPrice), 0);
  const potentialGrossProfit = totalRetailValuation - totalCostValuation;

  const completedSales = sales.filter(s => s.status === 'COMPLETED');
  const grossSalesRevenue = completedSales.reduce((acc, s) => acc + s.grandTotal, 0);
  const cogs = completedSales.reduce((acc, s) => acc + s.totalCost, 0);
  const realizedGrossProfit = grossSalesRevenue - cogs;
  const grossMarginPercent = grossSalesRevenue > 0 ? (realizedGrossProfit / grossSalesRevenue) * 100 : 0;

  const totalExpenses = expenses.reduce((acc, e) => acc + e.amount, 0);
  const netProfit = realizedGrossProfit - totalExpenses;
  const netMarginPercent = grossSalesRevenue > 0 ? (netProfit / grossSalesRevenue) * 100 : 0;

  const lowStockItems = items.filter(i => i.stock <= i.minStockAlert);
  const estimatedRestockCost = lowStockItems.reduce((acc, i) => {
    const needed = Math.max(10, (i.minStockAlert * 2) - i.stock);
    return acc + (needed * i.costPrice);
  }, 0);

  // Generate Comprehensive P&L Statement PDF
  const handleExportPnLPdf = () => {
    const doc = new jsPDF();
    doc.setFillColor(6, 78, 59);
    doc.rect(0, 0, doc.internal.pageSize.width, 24, 'F');
    
    doc.setTextColor(255, 255, 255);
    doc.setFontSize(14);
    doc.setFont('helvetica', 'bold');
    doc.text(settings.storeName.toUpperCase(), 14, 12);
    doc.setFontSize(10);
    doc.setFont('helvetica', 'normal');
    doc.text('STATEMENT OF PROFIT & LOSS (P&L)', 14, 19);

    doc.setTextColor(30, 41, 59);
    doc.setFontSize(9);
    doc.text(`Generated: ${new Date().toLocaleString()}`, 14, 32);
    doc.text(`Generated By: ${currentUser.name} (${currentUser.role})`, 14, 38);

    const summaryRows = [
      ['Gross Sales Revenue (A)', formatCurrency(grossSalesRevenue, settings.currencySymbol)],
      ['Cost of Goods Sold - COGS (B)', `-${formatCurrency(cogs, settings.currencySymbol)}`],
      ['Realized Gross Profit (A - B)', `${formatCurrency(realizedGrossProfit, settings.currencySymbol)} (${grossMarginPercent.toFixed(1)}%)`],
      ['Operating Expenses (C)', `-${formatCurrency(totalExpenses, settings.currencySymbol)}`],
      ['NET OPERATING PROFIT (A - B - C)', `${formatCurrency(netProfit, settings.currencySymbol)} (${netMarginPercent.toFixed(1)}%)`]
    ];

    autoTable(doc, {
      startY: 44,
      head: [['Financial Metric', `Amount (${settings.currencySymbol})`]],
      body: summaryRows,
      theme: 'grid',
      headStyles: { fillColor: [5, 150, 105], textColor: 255, fontStyle: 'bold' }
    });

    const finalY = (doc as any).lastAutoTable.finalY + 12;
    doc.setFont('helvetica', 'bold');
    doc.setFontSize(11);
    doc.text('Inventory Asset Health', 14, finalY);

    const inventoryRows = [
      ['Total Stock Units on Hand', items.reduce((acc, i) => acc + i.stock, 0).toString()],
      ['Total Inventory Cost Basis', formatCurrency(totalCostValuation, settings.currencySymbol)],
      ['Total Inventory Retail Valuation', formatCurrency(totalRetailValuation, settings.currencySymbol)],
      ['Unrealized Potential Gross Profit', formatCurrency(potentialGrossProfit, settings.currencySymbol)],
      ['Low Stock SKUs Requiring Reorder', lowStockItems.length.toString()],
      ['Estimated Reorder Budget Required', formatCurrency(estimatedRestockCost, settings.currencySymbol)]
    ];

    autoTable(doc, {
      startY: finalY + 4,
      head: [['Inventory Asset Metric', 'Value']],
      body: inventoryRows,
      theme: 'grid',
      headStyles: { fillColor: [30, 41, 59], textColor: 255, fontStyle: 'bold' }
    });

    doc.save(`${settings.storeName.replace(/\s+/g, '_')}_PnL_Report.pdf`);
  };

  return (
    <div className="space-y-4 pb-8">
      {/* Header */}
      <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-3 bg-white p-4 rounded-lg border border-emerald-100 shadow-sm">
        <div>
          <h1 className="text-lg font-bold text-slate-800 tracking-tight">
            Financial Analytics & Real-Time Reports
          </h1>
          <p className="text-xs text-slate-500">
            Export full spreadsheets, audit inventories, generate P&L profit sheets, and download starter templates.
          </p>
        </div>

        <div className="flex items-center gap-2">
          <button
            onClick={handleExportPnLPdf}
            className="h-8 px-3.5 bg-emerald-600 hover:bg-emerald-700 text-white rounded-md text-xs font-semibold shadow-xs transition-colors flex items-center gap-1.5"
          >
            <FileText className="w-3.5 h-3.5" />
            <span>Generate P&L Report PDF</span>
          </button>
        </div>
      </div>

      {/* Quick Downloadable Center Bar */}
      <div className="bg-[#064e3b] text-white p-4 rounded-lg border border-emerald-800 shadow-sm">
        <div className="flex flex-col md:flex-row md:items-center justify-between gap-4">
          <div>
            <span className="px-2 py-0.5 bg-emerald-500/20 text-emerald-300 text-[10px] font-bold rounded border border-emerald-400/30 uppercase tracking-wider">
              Official Spreadsheet Starter
            </span>
            <h2 className="text-sm font-bold mt-1">Download Standard Excel Inventory Template</h2>
            <p className="text-xs text-emerald-200/80 mt-0.5">
              Prefilled sample columns for SKU, Barcode, Title, Category, Cost, Price, Stock, and Min Alert.
            </p>
          </div>

          <button
            onClick={() => downloadExcelTemplate()}
            className="h-8 px-3.5 bg-emerald-500 hover:bg-emerald-400 text-emerald-950 font-bold rounded-md text-xs shadow-xs transition-all flex items-center justify-center gap-1.5 shrink-0"
          >
            <Download className="w-3.5 h-3.5" />
            <span>Download .XLSX Template</span>
          </button>
        </div>
      </div>

      {/* P&L Statement Grid */}
      <div className="grid grid-cols-1 lg:grid-cols-3 gap-4">
        {/* P&L Statement Card */}
        <div className="lg:col-span-2 bg-white rounded-lg p-4 border border-emerald-100 shadow-sm space-y-3">
          <div className="flex items-center justify-between pb-2.5 border-b border-slate-100">
            <h3 className="font-bold text-slate-800 text-sm">Statement of Profit & Loss (P&L)</h3>
            <span className="text-[11px] font-mono text-slate-400">Real-Time Ledger</span>
          </div>

          <div className="space-y-2 text-xs font-mono">
            {/* Gross Revenue */}
            <div className="p-2.5 rounded bg-slate-50 flex items-center justify-between">
              <div>
                <p className="font-bold text-slate-800 font-sans">Gross Sales Revenue</p>
                <p className="text-[10px] text-slate-500 font-sans">Completed POS sales orders</p>
              </div>
              <span className="font-bold text-sm text-slate-900">
                {formatCurrency(grossSalesRevenue, settings.currencySymbol)}
              </span>
            </div>

            {/* COGS */}
            <div className="p-2.5 rounded bg-slate-50 flex items-center justify-between">
              <div>
                <p className="font-bold text-slate-800 font-sans">Cost of Goods Sold (COGS)</p>
                <p className="text-[10px] text-slate-500 font-sans">Wholesale purchase cost of items sold</p>
              </div>
              <span className="font-bold text-sm text-slate-600">
                -{formatCurrency(cogs, settings.currencySymbol)}
              </span>
            </div>

            {/* Gross Profit */}
            <div className="p-2.5 rounded bg-emerald-50/60 border border-emerald-100 flex items-center justify-between">
              <div>
                <p className="font-bold text-emerald-950 font-sans">Realized Gross Profit</p>
                <p className="text-[10px] text-emerald-700 font-sans">Gross Margin: {grossMarginPercent.toFixed(1)}%</p>
              </div>
              <span className="font-bold text-sm text-emerald-800">
                +{formatCurrency(realizedGrossProfit, settings.currencySymbol)}
              </span>
            </div>

            {/* Expenses */}
            <div className="p-2.5 rounded bg-slate-50 flex items-center justify-between">
              <div>
                <p className="font-bold text-slate-800 font-sans">Operating Expenses</p>
                <p className="text-[10px] text-slate-500 font-sans">Rent, utilities, wages, marketing</p>
              </div>
              <span className="font-bold text-sm text-rose-700">
                -{formatCurrency(totalExpenses, settings.currencySymbol)}
              </span>
            </div>

            {/* Net Income */}
            <div className={`p-3 rounded-md border flex items-center justify-between ${
              netProfit >= 0
                ? 'bg-emerald-100/50 border-emerald-300'
                : 'bg-rose-50 border-rose-300'
            }`}>
              <div>
                <p className="font-bold text-xs uppercase tracking-wider font-sans">NET OPERATING PROFIT</p>
                <p className="text-[10px] text-slate-600 font-sans">
                  Net Margin: {netMarginPercent.toFixed(1)}%
                </p>
              </div>
              <span className={`font-bold text-lg ${
                netProfit >= 0 ? 'text-emerald-900' : 'text-rose-700'
              }`}>
                {formatCurrency(netProfit, settings.currencySymbol)}
              </span>
            </div>
          </div>
        </div>

        {/* Inventory Restock Forecasting & Budget */}
        <div className="bg-white rounded-lg p-4 border border-emerald-100 shadow-sm flex flex-col justify-between space-y-3">
          <div>
            <div className="flex items-center gap-2 pb-2.5 border-b border-slate-100">
              <AlertTriangle className="w-4 h-4 text-orange-600" />
              <h3 className="font-bold text-slate-800 text-sm">Replenishment Forecast</h3>
            </div>

            <div className="mt-3 space-y-2">
              <div className="p-2.5 rounded bg-orange-50/60 border border-orange-200">
                <span className="text-[10px] font-bold text-orange-900 uppercase">Critical Reorder SKUs</span>
                <p className="text-xl font-bold text-orange-900 mt-0.5">{lowStockItems.length}</p>
                <p className="text-[10px] text-orange-700">Items currently at or below alert limit.</p>
              </div>

              <div className="p-2.5 rounded bg-slate-50 border border-slate-200">
                <span className="text-[10px] font-bold text-slate-500 uppercase">Estimated Restock Budget</span>
                <p className="text-base font-bold text-slate-800 font-mono mt-0.5">
                  {formatCurrency(estimatedRestockCost, settings.currencySymbol)}
                </p>
                <p className="text-[10px] text-slate-500">Based on default safety target restock qty.</p>
              </div>
            </div>
          </div>

          <button
            onClick={() => exportInventoryToPdf(lowStockItems, settings)}
            disabled={lowStockItems.length === 0}
            className="w-full h-8 bg-slate-800 hover:bg-slate-700 disabled:opacity-40 text-white rounded-md text-xs font-semibold transition-colors flex items-center justify-center gap-1.5"
          >
            <Download className="w-3.5 h-3.5" />
            <span>Export Low Stock Purchase Order PDF</span>
          </button>
        </div>
      </div>

      {/* Export Modules Directory */}
      <div className="bg-white rounded-2xl p-6 border border-slate-200/80 shadow-xs space-y-4">
        <h3 className="font-bold text-sm text-slate-900">Real-Time Data Export Hub</h3>
        
        <div className="grid grid-cols-1 sm:grid-cols-3 gap-4">
          {/* Inventory */}
          <div className="p-4 rounded-xl border border-slate-200 bg-slate-50/50 space-y-2.5">
            <div className="flex items-center gap-2">
              <Boxes className="w-5 h-5 text-emerald-700" />
              <h4 className="font-bold text-xs text-slate-900">Catalog & Stock Valuation</h4>
            </div>
            <p className="text-[11px] text-slate-500">
              Complete product inventory, barcodes, cost basis, and margins.
            </p>
            <div className="flex gap-2 pt-1">
              <button
                onClick={() => exportInventoryToExcel(items, settings)}
                className="flex-1 py-1.5 bg-white border border-slate-200 hover:border-emerald-500 text-slate-700 rounded-lg text-xs font-bold transition-colors flex items-center justify-center gap-1"
              >
                <FileSpreadsheet className="w-3.5 h-3.5 text-emerald-600" /> Excel
              </button>
              <button
                onClick={() => exportInventoryToPdf(items, settings)}
                className="flex-1 py-1.5 bg-white border border-slate-200 hover:border-emerald-500 text-slate-700 rounded-lg text-xs font-bold transition-colors flex items-center justify-center gap-1"
              >
                <FileText className="w-3.5 h-3.5 text-emerald-600" /> PDF
              </button>
            </div>
          </div>

          {/* Sales */}
          <div className="p-4 rounded-xl border border-slate-200 bg-slate-50/50 space-y-2.5">
            <div className="flex items-center gap-2">
              <TrendingUp className="w-5 h-5 text-emerald-700" />
              <h4 className="font-bold text-xs text-slate-900">Sales & Invoicing Ledger</h4>
            </div>
            <p className="text-[11px] text-slate-500">
              Every completed POS order, tax collected, and customer memo.
            </p>
            <div className="flex gap-2 pt-1">
              <button
                onClick={() => exportSalesToExcel(sales, settings)}
                className="flex-1 py-1.5 bg-white border border-slate-200 hover:border-emerald-500 text-slate-700 rounded-lg text-xs font-bold transition-colors flex items-center justify-center gap-1"
              >
                <FileSpreadsheet className="w-3.5 h-3.5 text-emerald-600" /> Excel
              </button>
              <button
                onClick={() => exportSalesToPdf(sales, settings)}
                className="flex-1 py-1.5 bg-white border border-slate-200 hover:border-emerald-500 text-slate-700 rounded-lg text-xs font-bold transition-colors flex items-center justify-center gap-1"
              >
                <FileText className="w-3.5 h-3.5 text-emerald-600" /> PDF
              </button>
            </div>
          </div>

          {/* Expenses */}
          <div className="p-4 rounded-xl border border-slate-200 bg-slate-50/50 space-y-2.5">
            <div className="flex items-center gap-2">
              <TrendingDown className="w-5 h-5 text-rose-700" />
              <h4 className="font-bold text-xs text-slate-900">Operating Expenses</h4>
            </div>
            <p className="text-[11px] text-slate-500">
              Categorized business expenses, vendors, and payment receipts.
            </p>
            <div className="flex gap-2 pt-1">
              <button
                onClick={() => exportExpensesToExcel(expenses, settings)}
                className="flex-1 py-1.5 bg-white border border-slate-200 hover:border-emerald-500 text-slate-700 rounded-lg text-xs font-bold transition-colors flex items-center justify-center gap-1"
              >
                <FileSpreadsheet className="w-3.5 h-3.5 text-emerald-600" /> Excel
              </button>
              <button
                onClick={() => exportExpensesToPdf(expenses, settings)}
                className="flex-1 py-1.5 bg-white border border-slate-200 hover:border-emerald-500 text-slate-700 rounded-lg text-xs font-bold transition-colors flex items-center justify-center gap-1"
              >
                <FileText className="w-3.5 h-3.5 text-emerald-600" /> PDF
              </button>
            </div>
          </div>
        </div>
      </div>
    </div>
  );
};
